#+STARTUP: indent
* Overview
Run macOS Mojave (10.14) or Catalina (10.15) on an Acer Swift3 SF315 52G.
Most pieces are fully supported, and this setup can be used as your main machine. A few pieces are missing (and some will probably never be supported). Caveats in the Hardware section.
You can use the EFI folder to be to boot into a USB installer, or for regular booting.
** Hackintosh Mojave + Catalina Acer-Swift3-SF315-52G
  - CPU : Intel Core i5-8250U (Kabylake-R)
  - Graphics : Intel UHD 620 (+ MX150)
  - RAM : SK Hynix HMA81GS6CJR8N-VK 8 GB DDR4 2666 MHz (On board + One slot)
  - SSD : Hynix 256GB M.2 SOLID STATE DRIVE 80MM L (HFS256G39TND-N210A) Read : Up to 530MB/s(128/256/512GB)\ Write : Up to 190MB/s(128GB)
  - Screen : 15.5-inch 1920 x 1080 glossy IPS
  - Ports : 1xUSB 3.1 Gen-1 Type-C, 2xUSB 3.0, 1xUSB 2.0, 1xHDMI (full-size), 1xAudio jack
  - Wifi/Bluetooth : Intel AC-7265, (M.2 NGFF)
  - Audio : ALC256
  - SD Card Reader : Realtek USB2.0-CRW (ven id:0bda, dev id:0129)
  - Back-lit keyboard
  - Controller (Synaptic): VoodooI2CHID, VoodooI2C + PS2Controller
** What is working
  - Graphics: Intel UHD Graphics 620 (Disable MX150)
  - Audio: Speakers, headphones (Mic don't work)
  - Keyboard: Backlight is ACPI-managed so it works just fine too
  - Trackpad: VoodooI2CHID,VoodooI2C,VoodooI2CSynaptics makes it buttery-smooth, supports all the macOS gestures
  - USB: Full support
  - Webcam: PhotoBooth works fine
  - Sleep/Wake: works very well
  - Wifi/Bluetooth: You need replace Broadcom BCM94352Z
** What is not working
  - Mic: I tried many ways but it not works
  - HDMI: Just works after Sleep/Wake, LOL
* Hardware
** Graphics
Integrated Intel UHD Graphics 620 support is handled by [[https://github.com/acidanthera/WhateverGreen][WhateverGreen]], and configured in the
=PciRoot(0x0)/Pci(0x2,0x0)= section of config.plist. The Nvidia GPU MX150 is not supported due to hardware differences and lack of driver support in macOS. It is disabled to save power.
*** Installtion 
- config.plist
  - =Devices/Properties/PciRoot(0x0)/Pci(0x2,0x0)=
    - =AAPL,GfxYTile: 01000000=
    - =AAPL,ig-platform-id: 00001659=
    - =AAPL,slot-name: Internal@0,2,0=
    - =device-id: 16590000=
    - =device_type: VGA compatible controller=
    - =disable-external-gpu: 01000000= (Disable GPU or -wegnoegpu with Boot Flags)
    - =enable-hdmi-dividers-fix: 01000000=
    - =enable-hdmi20: 01000000=
    - =framebuffer-con0-busid: 00000000=
    - =framebuffer-con0-enable: 01000000=
    - =dframebuffer-con0-flags: 98000000=
    - =framebuffer-con0-index: 00000000=
    - =framebuffer-con0-pipe: 12000000=
    - =framebuffer-con0-type: 02000000=
    - =framebuffer-con1-busid: 05000000=
    - =framebuffer-con1-enable: 01000000=
    - =framebuffer-con1-flags: 87010000=
    - =framebuffer-con1-index: 01000000=
    - =framebuffer-con1-pipe: 12000000=
    - =framebuffer-con1-type: 00080000=
    - =framebuffer-con2-busid: 04000000=
    - =framebuffer-con2-enable: 01000000=
    - =framebuffer-con2-flags: 87010000=
    - =framebuffer-con2-index: 02000000=
    - =framebuffer-con2-pipe: 12000000=
    - =framebuffer-con2-type: 00080000=
    - =framebuffer-con3-busid: 00000000=
    - =framebuffer-con3-enable: 01000000=
    - =framebuffer-con3-flags: 20000000=
    - =framebuffer-con3-index: FFFFFFFF=
    - =framebuffer-con3-pipe: 00000000=
    - =framebuffer-con3-type: 01000000=
    - =framebuffer-patch-enable: 01000000=
    - =hda-gfx: onboard-1=
To determine if Intel GPU (IGPU) acceleration is working, check: About This Mac -> Intel UHD Graphics 620
1536 MB. A value less than 1536MB indicates a problem (e.g. 7MB or 31MB are common).
** Touchpad
Acer-Swift3-SF315-52G using Touchpad Synaptic. If only using VoodooI2C and VoodooPS2Controller it will not work smoothly, you need to patch [[https://github.com/linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G/blob/master/Patch%20I2C/SSDT-I2C.dsl][SSDT-I2C]] to be able to use as a real Trackpad of Macbook 
** Wi-Fi/Bluetooth
*** Installation
- Include [[https://github.com/acidanthera/AirportBrcmFixup][AirportBrcmFixup]] for Wi-Fi
- Include [[https://github.com/acidanthera/BrcmPatchRAM/releases][BrcmPatchRAM]] for Bluetooth (for installation to CLOVER/kexts/Other)
** Messages and FaceTime
You can try this tips https://hackintosher.com/guides/quick-fixes-facetime-icloud-imessage-hackintosh-not-working/ or https://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/
** Battery status
Install =SMCBatteryManager.kext= that comes with [[https://github.com/acidanthera/virtualsmc/releases][VirtualSMC]] to get battery status. Ensure that you have removed ACPIBatteryManager if you’ve installed it previously.
** Audio 
Audio on the Acer Swift3 SF315 52G is based on the Realtek ALC256 audio codec. The ALC256 is not supported on macOS by default, so we use AppleALC to enable it. Audio pipelines on laptops appear to have unique amplifier and gain setups, so we need to pass a layout-id to AppleALC compatible with the Acer Swift3 SF315 52G. The only ID that works well is layout-id=17.
*** Installtion 
- config.plist
  - =Devices/Properties/PciRoot(0x0)/Pci(0x1f,0x3)=
    - =AAPL,slot-name: Internal=
    - =hda-gfx: onboard-1=
    - =hda-idle-support: 1=
    - =layout-id: 17=
    - =model: Intel Sunrise Point-LP HD Audio=
** USB
Has a few incorrect USB properties, but we can inject the correct properties via USBInjectAll with [[https://github.com/RehabMan/OS-X-USB-Inject-All/blob/master/SSDT-UIAC.dsl][SSDT-UIAC.]]
